### ISSUE TITLE
libwhisper.a not found

### ISSUE THREAD

**Issue by Liftoff-Studios** [tazz4843/whisper-rs#20]
Hi, I tried installing whisper-rs on windows. 

First there was an error saying no clang found so I installed llvm using Choco

But now I get this error

![image](https://user-images.githubusercontent.com/84321034/226102049-9ce553ed-7221-4f84-a0a5-0c004a0985c6.png)
Since it said libwhisper.a wasn't found I went to the lib folder but I couldnt find it there

Any help would be greatly appreciated !

**Comment by tazz4843** [comment]
Switch your whisper-rs dependency to the Git version until I make a release.

**Comment by tazz4843** [comment]
Fixed in 0.5.0

**Comment by ShayBox** [comment]
This still occurs for me with the cargo crate 0.5.0, but not with the git repo, it appears the build.rs script in cache with cargo 0.5.0 doesn't match with the git repo.

**Comment by tazz4843** [comment]
Interesting. I'm probably going to upgrade whisper.cpp later tonight and make a new release anyways, hopefully that fixes your issue.
